[tools]
"ubi:jesseduffield/lazygit" = "0.56.0"
lua = "5.1"
"ubi:JohnnyMorganz/stylua" = "2.3.1"


[tasks]
test = "luarocks test --local"
test-focus = "luarocks test --local -- --filter focus"
format = "stylua lua/ spec/ integration-tests/"

[tasks.check]
description = "Check the code for errors (lint + test + format)"
depends = ["lint", "test", "format"]

[tasks.build]
description = "Install dependencies"
run = """
luarocks init --no-gitignore
luarocks install busted 2.2.0-1

mise tasks
"""

[tasks.lint]
description = "Lint the codebase"
run = """
selene ./lua/ ./spec/

if rg "#focus" --glob "*.lua" ./spec/; then
  echo "\n";
  echo "Error: {{ vars.COLOR_GREEN }}#focus{{ vars.COLOR_RESET }} tags found in the codebase.\n";
  echo "Please remove them to prevent issues with not accidentally running all tests.";
  exit 1; \
fi
"""

[vars]
COLOR_RESET = '\033[0m'
COLOR_GREEN = '\033[1;32m'
