package = "tsugit.nvim"
version = "0.1.0"
lua = "==5.1"

[description]
maintainer = "Mika Vilpas"
labels = ["nvim"]
license = "MIT"

[test_dependencies]
busted = "2.2.0-1"
nlua = "0.3.2-1"

[test]
type = "busted"

[build]
type = "builtin"
