# # yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
#
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

disableStartupPopups: true
gui:
  # showFileTree makes it possible to assert that files are currently selected
  # in the Files pane. Otherwise the full path to the file is shown, and it's
  # too long to fully fit in the view
  showFileTree: true
  commitHashLength: 0
  nerdFontsVersion: "3"
os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  editAtLineAndWait: "nvim +{{line}} {{filename}}"
promptToReturnFromSubprocess: false
