name: Documentation
on: [pull_request]
permissions:
  contents: read
jobs:
  check-links:
    uses: mikavilpas/dotfiles/.github/workflows/docs.yml@c798d2e752ff290bbc1c5b602abb8e30bc2464da # main
    secrets: inherit
